### ISSUE TITLE
A Method FixCpoy Based on CraftTweaker

### ISSUE THREAD

**Issue by Yorunina** [SkyIce0229/FixCopy#2]
提供一种基于 1.18.2 CraftTweaker的修复方法，希望能够在校验后帮忙排版进来。
其他版本的语法类似，只是在事件注册上可能有所区别。
```
import crafttweaker.api.events.CTEventManager;

CTEventManager.register<crafttweaker.api.event.block.BlockBreakEvent>((event) => {
    if(event.state.block.registryName.getNamespace() == "storagedrawers" && event.player.name.getContents() == "Deployer"){
        event.world.setBlockAndUpdate(event.getPos(), <blockstate:minecraft:air>); // 机械手破坏方块后方块消失
        //event.cancel(); // 二选一，解除本行注释并注释掉上一行即为禁止破坏
    }
});
```
![修复](https://github.com/SkyIce0229/FixCopy/assets/61814528/1b3f1557-607c-4788-82af-5001f44459bf)

**Comment by SkyIce0229** [comment]
非常抱歉现在才看到你的issue，经过我单人验证后发现`event.player.name.getContents() == "Deployer"`会让if一直为false，但还是非常感谢你提供的代码。你写完这串代码是在服务器中验证的吗？

**Comment by Yorunina** [comment]
> 非常抱歉现在才看到你的issue，经过我单人验证后发现`event.player.name.getContents() == "Deployer"`会让if一直为false，但还是非常感谢你提供的代码。你写完这串代码是在服务器中验证的吗？

在你回复的时候，Create进行了一次更新，使得机械手总会携带玩家的UUID以解决Fake Player的潜在问题，进而导致该方案失效。该issue可以关闭。
